### ISSUE TITLE
HTML isnt being converted when opening an email.

### ISSUE THREAD

**Issue by nenntendo64** [Intro-to-SE-Lab-Fall-20/Group-1#43]
Opening an email in the inbox page does not convert the body correctly. It is displaying all the HTML tags as just a giant body. Need to find a way to convert it to actual HTML so that the emails look as intended.

**Comment by nenntendo64** [comment]
Note: Works for some emails that contain images or stylized emails (ex: 
![image](https://user-images.githubusercontent.com/45054998/96025488-ce6b2900-0e1a-11eb-8e69-2f95fcd93deb.png)
)

Others it just displays the raw HTML(ex: 
![image](https://user-images.githubusercontent.com/45054998/96025553-e773da00-0e1a-11eb-8b50-57e3b575e87d.png))

**Comment by jameswatters1** [comment]
I fixed this issue, I will submit it with the download attachment PR
