### ISSUE TITLE
Messages from TinyMCE have weird UTF-8 encodings

### ISSUE THREAD

**Issue by pbell97** [Intro-to-SE-Lab-Fall-20/Group-1#51]
TinyMCE messages have weird UTF-8 encodings at beginning and end that needs to be parsed out.

Deals with how we display the email, not how we are sending it.

![](https://cdn.discordapp.com/attachments/747535503255142563/766693783177789451/unknown.png)

**Comment by nenntendo64** [comment]
Note: Appears that this only happens when messages are sent to ourselves from within the app. Probably has something to do with how we are capturing the text from within the TinyMCE editor

**Comment by pbell97** [comment]
> Note: Appears that this only happens when messages are sent to ourselves from within the app. Probably has something to do with how we are capturing the text from within the TinyMCE editor

@nenntendo64 Atleast on my end, they are displayed correctly on the actual Gmail client but not in our client. So I think it has to do with how they are displayed and not captured from TinyMCE.
